import Head from "next/head";
import Link from "next/link";
import { api } from " /utils/api";
import { SignInButton, SignOutButton } from "@clerk/nextjs";
import { ClerkProvider, useUser, SignIn, SignedOut } from "@clerk/nextjs";

export default function Home() {
  const { isLoaded, isSignedIn, user } = useUser();

  console.log(user);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b ">
        <p>hello</p>
        {isSignedIn ? <SignOutButton /> : <SignInButton />}
      </main>
    </>
  );
}
